language: R
r:
    - release
    - olderel
    - devel
before_install:
    - R -e 'install.packages("devtools")'
    - R -e 'install.packages("covr")'

install:
    - R -e 'devtools::install_deps(dep=T)'

script:
    - R CMD build
    - R CMD check *tar.gz
after:success:
    - Rscript -e 'covr'
