language: R
r:
    - release
    - olderel
    - devel
before_install:
    - E -e 'install.packages("devtools")'

install:
    - E -e 'devtools::install_deps(dep=T)'

script:
    - R CMD build
    - R CMD check *tar.gz
